many improvements and changes
added support for multiple sources, removed support for stin source, removed compression level 0, custom install script is now always optional, always creates a tar, now

diff --git a/mkinst b/mkinst
--- a/mkinst
+++ b/mkinst
@@ -19,14 +19,14 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 version="0.0.1"
-include=""
+include="echo tar xzopPf \$tmp"
 instshell="/bin/sh"
 verbose=true
 compress=6
 tempfiles=()
 
 function showusage {
-    echo "usage: $(basename $0) [OPTIONS] [--] <target> <source>
+    echo "usage: $(basename $0) [OPTIONS] [--] <target> <source> [<source> ...]
 
 Creates a self-contained installer from the specified source and stores it to
 the specified target.
@@ -34,11 +34,7 @@ the specified target.
 ARGUMENTS
 
     <target>            Either a file-name or '-' for stdout.
-    <source>            Expects a file-name, a directory name or '-' for stdin.
-                        If the name of a directory is specified, the tool will
-                        create a tar archive from it. If the source is no direc-
-                        tory an additional custom installer script needs to be
-                        added using the options '-i' or '--include'.
+    <source>            One or multiple file or directory names.
 
 OPTIONS
 
@@ -47,14 +43,9 @@ OPTIONS
                         Make sure that the shell is available on the target
                         system. The specified path should be valid to use as
                         shebang.
-    -i, --include ARG   Additional custom installer script to include. This
-                        option is required if the source is either a file or
-                        stdin. It is optional if the source is a directory.
-    -c, --compress ARG  Compression level (default: $compress).
-                        Please see the gzip man pages for details. Additionally
-                        to the gzip compression levels the level 0 was added
-                        to specify that the payload should be distributed un-
-                        compressed.
+    -i, --include ARG   Additional custom installer script to include.
+    -c, --compress ARG  Compression level (default: $compress). Please see the
+                        gzip man pages for details.
     -h, --help          Display this usage information.
         --version       Show version and exit.
 "
@@ -93,7 +84,7 @@ while [[ "${1:0:1}" = "-" ]]; do
             verbose=false
             ;;
         -c|--compress)
-            if ! [[ $2 =~ ^[0-9]$ ]] ; then
+            if ! [[ $2 =~ ^[1-9]$ ]] ; then
                log "Invalid compression level."
                exit 1
             fi
@@ -102,7 +93,15 @@ while [[ "${1:0:1}" = "-" ]]; do
             shift
             ;;
         -i|--include)
-            include="$2"
+            if [ "$2" = "" ]; then
+                log "Custom installer script is missing."
+                exit 1
+            elif [ ! -f "$2" ] && [ ! -p "$2" ]; then
+                log "Unable to acquire custom installer script."
+                exit 1
+            fi
+
+            include="cat "$include""
             shift
             ;;
         -s|--shell)
@@ -136,46 +135,26 @@ else
     dst="$1"
 fi
 
-if [ "$include" != "" ]; then
-    if [ ! -f "$include" ] && [ ! -p "$include" ]; then
-        log "Unable to acquire custom installer script."
-        exit 1
+shift
+
+error=false
+
+for i in $@; do
+    if [ ! -f "$i" ] && [ ! -d "$i" ]; then
+        log "No such file or directory: $i"
+        error=true
     fi
+done
 
-    include="cat "$include""
-fi
-
-if [ "$2" = "-" ] || [ -f "$2" ]; then
-    if [ "$include" = "" ]; then
-        showusage
-        exit 1
-    fi
-
-    src=$(mktemp 2>/dev/null || mktemp -t "tmp.XXXXXXXXXX")
-    addtemp "$src"
-
-    if [[ $compress -gt 0 ]]; then
-        cat "$2" | gzip -$compress > "$src"
-    else
-        cat "$2" > "$src"
-    fi
-elif [ -d "$2" ]; then
-    src=$(mktemp 2>/dev/null || mktemp -t "tmp.XXXXXXXXXX")
-    addtemp "$src"
-
-    if [[ $compress -gt 0 ]]; then
-        tar cf - -C "$2" . | gzip -$compress > "$src"
-    else
-        tar cf "$src" -C "$2" .
-    fi
-
-    if [ "$include" = "" ]; then
-        include="echo tar xopPf \$tmp"
-    fi
-else
-    log "Unable to read from source."
+if [[ $error = true ]]; then
+    log "Exiting with failure status due to previous errors."
     exit 1
 fi
+
+src=$(mktemp 2>/dev/null || mktemp -t "tmp.XXXXXXXXXX")
+addtemp "$src"
+
+tar cf - $@ | gzip -$compress > "$src"
 
 check=($(CMD_ENV=xpg4 cksum "$src"))
 line=$(($(grep -n "#""MARKER:INSTALLER" "$0" | head -n 1 | cut -d ":" -f 1) + 1))
@@ -190,10 +169,6 @@ tail +$line "$0" \
     | cat - <($include) <(echo "exit") > "$tmp"
 
 extract="tail +$(($(cat $tmp | wc -l) + 1)) \$0"
-
-if [[ $compress -gt 0 ]]; then
-    extract="$extract | gunzip"
-fi
 
 sed -e "s;%%EXTRACT%%;$extract;g" "$tmp" | cat - "$src" > "$dst"
 
